package view;

import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 * This class defines the main menu of the application. Actions that can be 
 * done: insert, read, delete, update, readAll.
 * @author Francesc Perez
 * @version 1.1.0
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
         try {
            setIconImage(new ImageIcon(ImageIO.read(new File("images/logo.png"))).getImage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Application logo is not available", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }

    public JButton getInsert() {
        return insert;
    }

    public JButton getRead() {
        return read;
    }

    public JButton getDelete() {
        return delete;
    }

    public JButton getUpdate() {
        return update;
    }

    public JButton getReadAll() {
        return readAll;
    }
    
    public JButton getDeleteAll() {
        return deleteAll1;
                }
    public JButton getCount(){
        return deleteAll;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        read = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        readAll = new javax.swing.JButton();
        deleteAll = new javax.swing.JButton();
        deleteAll1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - People v1.1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(300, 450));

        read.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        read.setText("READ");
        read.setMaximumSize(new java.awt.Dimension(120, 50));
        read.setMinimumSize(new java.awt.Dimension(120, 50));
        read.setPreferredSize(new java.awt.Dimension(120, 50));

        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.setMaximumSize(new java.awt.Dimension(120, 50));
        delete.setMinimumSize(new java.awt.Dimension(120, 50));
        delete.setPreferredSize(new java.awt.Dimension(120, 50));

        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.setMaximumSize(new java.awt.Dimension(120, 50));
        update.setMinimumSize(new java.awt.Dimension(120, 50));
        update.setPreferredSize(new java.awt.Dimension(120, 50));

        insert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insert.setText("INSERT");
        insert.setMaximumSize(new java.awt.Dimension(120, 50));
        insert.setMinimumSize(new java.awt.Dimension(120, 50));
        insert.setPreferredSize(new java.awt.Dimension(120, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Author: francesc.perez@stucom.com - Version 1.1.0");

        readAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        readAll.setText("READ ALL");
        readAll.setMaximumSize(new java.awt.Dimension(120, 50));
        readAll.setMinimumSize(new java.awt.Dimension(120, 50));
        readAll.setPreferredSize(new java.awt.Dimension(120, 50));

        deleteAll.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteAll.setText("COUNT");
        deleteAll.setMaximumSize(new java.awt.Dimension(120, 50));
        deleteAll.setMinimumSize(new java.awt.Dimension(120, 50));
        deleteAll.setPreferredSize(new java.awt.Dimension(120, 50));
        deleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllActionPerformed(evt);
            }
        });

        deleteAll1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteAll1.setText("DELETE ALL");
        deleteAll1.setMaximumSize(new java.awt.Dimension(120, 50));
        deleteAll1.setMinimumSize(new java.awt.Dimension(120, 50));
        deleteAll1.setPreferredSize(new java.awt.Dimension(120, 50));
        deleteAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAll1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readAll, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(readAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(deleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAll1ActionPerformed
   private void deleteAllActionPerformed(java.awt.event.ActionEvent evt){
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton deleteAll;
    private javax.swing.JButton deleteAll1;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton read;
    private javax.swing.JButton readAll;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
